/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_scu_csaserver_utils_KeyNode */

#ifndef _Included_edu_scu_csaserver_utils_KeyNode
#define _Included_edu_scu_csaserver_utils_KeyNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_scu_csaserver_utils_KeyNode
 * Method:    getKeyNode
 * Signature: (I[[I)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_scu_csaserver_utils_KeyNode_getKeyNode
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
